# Initialize list of class label names
CLASSES = ["Sonus-naturalis", "Fringilla-coelebs", "Parus-major",
"Turdus-merula", "Turdus-philomelos", "Sylvia-communis", "Emberiza-citrinella",
"Sylvia-atricapilla", "Emberiza-calandra", "Phylloscopus-trochilus", 
"Luscinia-megarhynchos", "Strix-aluco", "Phylloscopus-collybita",
"Carduelis-carduelis", "Erithacus-rubecula", "Chloris-chloris",
"Sylvia-borin", "Acrocephalus-arundinaceus", "Acrocephalus-dumetorum",
"Oriolus-oriolus", "Troglodytes-troglodytes", "Bubo-bubo",
"Ficedula-parva", "Linaria-cannabina", "Luscinia-svecica",
"Alauda-arvensis", "Luscinia-luscinia", "Phoenicurus-phoenicurus",
"Aegolius-funereus", "Cyanistes-caeruleus", "Hirundo-rustica",
"Emberiza-cirlus", "Locustella-naevia", "Cuculus-canorus",
"Sylvia-curruca", "Loxia-curvirostra", "Emberiza-hortulana",
"Carpodacus-erythrinus", "Athene-noctua", "Crex-crex", "Acrocephalus-schoenobaenus",
"Acrocephalus-palustris", "Periparus-ater", "Phylloscopus-sibilatrix",
"Emberiza-schoeniclus", "Hippolais-icterina", "Pyrrhula-pyrrhula",
"Caprimulgus-europaeus", "Ficedula-hypoleuca", "Glaucidium-passerinum",
]
